config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  get 'books/search' => 'books#search'
  resources :books
  resources :authors

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :author

  validates :title, presence: true
  validates :author, presence: true
  
  def title_and_author
    "#{self.title}: by #{self.author.full_name}"
  end

  def self.search(search)
    where("title like ?", "%#{search}%")
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if params[:search]
      @books = Book.search(params[:search]).order('created_at DESC')
    else
      @books = Book.all.order('created_at DESC')
    end
  end

  def show
    @book = Book.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/index.html.erb
<h1>Here are the authors!</h1>
<hr/>

<% @authors.each do |author| %>
  <p><%= link_to author.full_name, author_path(author) %></p>
  <p>Number of books reviewed:<%= author.books.count %></p>
<% end %>

app/views/authors/show.html.erb
<h1>Showing: <%= @author.full_name %></h1>
<hr/>

app/views/books/index.html.erb
<h1>Here are the books</h1>
<div class='pull-right'>
  <%= form_tag(books_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Books" %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>
<hr/>

<% @books.each do |book| %>
  <h3><%= link_to book.title, book_path(book) %></h3>
  <p><%= link_to book.author.full_name, author_path(book.author) %></p>
<% end %>

app/views/books/show.html.erb
<h1>You are looking at the book!( <%= @book.title %> )</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='container-fluid'>

<%= yield %>

</body>
</html>